repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.8.0
    hooks:
      - id: isort

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8.git
    rev: 3.9.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
        language_version: python3
        args: [--config, .flake8]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: debug-statements
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-builtin-literals
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-docstring-first
      - id: requirements-txt-fixer

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.971
    hooks:
    - id: mypy
      additional_dependencies:
        - sqlalchemy[mypy]>=1.4.29
        - typing-extensions
        - types-requests
